"""portr8 report generator — creates Markdown reports from run data."""

from datetime import datetime
from pathlib import Path
from lib.models import RunSummary
from lib.generator import to_tilde_path


def generate_report(summary: RunSummary, output_dir: Path) -> Path:
    """Generate a README.md report for a portr8 run.
    
    The report includes:
    - Run configuration (with software version)
    - Score progression table (3-axis: Facial, Scene, Adherence)
    - Best/worst iterations
    - Convergence status
    - Embedded images (relative paths)
    
    Returns: Path to the generated README.md
    """
    report_path = output_dir / "README.md"
    
    version = summary.config.portr8_version
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    lines = []
    lines.append(f"# portr8 v{version} — {summary.config.character}")
    lines.append(f"")
    lines.append(f"*Generated by portr8 v{version} on {timestamp}*")
    lines.append(f"")
    
    # Status banner
    if summary.converged:
        lines.append(f"> **CONVERGED** — Target {summary.config.target_score}/10 achieved!")
    else:
        lines.append(f"> **FAILED** — Did not reach target {summary.config.target_score}/10 after {len(summary.iterations)} iterations")
    lines.append(f"")
    
    # Configuration
    lines.append(f"## Configuration")
    lines.append(f"")
    lines.append(f"| Parameter | Value |")
    lines.append(f"|:---|:---|")
    lines.append(f"| Prompt | {summary.config.prompt} |")
    lines.append(f"| Character | {summary.config.character} |")
    lines.append(f"| Target Score | {summary.config.target_score}/10 |")
    lines.append(f"| Max Iterations | {summary.config.max_iterations} |")
    lines.append(f"| Image Type | {summary.config.image_type} |")
    lines.append(f"| Image Model | {summary.config.image_model} |")
    lines.append(f"| Judge Model | {summary.config.judge_model} |")
    lines.append(f"| portr8 Version | {summary.config.portr8_version} |")
    lines.append(f"")
    
    # Score Progression
    lines.append(f"## Score Progression")
    lines.append(f"")
    
    characters = summary.config.characters or ([summary.config.character] if summary.config.character else [])
    is_multi = len(characters) > 1
    
    if is_multi:
        headers = ["Iter"] + [f"F{i+1} ({c.capitalize()})" for i, c in enumerate(characters)] + ["Scene", "Adherence", "Media", "Strategy", "Verdict", "Time"]
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("| " + " | ".join([":---:"] * (len(headers) - 3) + [":---", ":---", ":---:"]) + " |")
        for r in summary.iterations:
            f_scores_row = [
                f"{r.verdict.character_facial_scores[i]:.1f}" if len(r.verdict.character_facial_scores) > i else f"{r.verdict.facial_similarity:.1f}"
                for i in range(len(characters))
            ]
            row = (
                [str(r.iteration)]
                + f_scores_row
                + [
                    f"{r.verdict.scene_adaptation:.1f}",
                    f"{r.verdict.adherence_score:.1f}",
                    f"{r.verdict.average_score:.1f}",
                    r.strategy,
                    _strip_emoji(r.verdict.verdict_label),
                    f"{r.elapsed_seconds:.1f}s",
                ]
            )
            lines.append("| " + " | ".join(row) + " |")
    else:
        lines.append(f"| Iter | Facial | Scene | Adherence | Media | Strategy | Verdict | Time |")
        lines.append(f"|:---:|:---:|:---:|:---:|:---:|:---|:---|:---:|")
        for r in summary.iterations:
            lines.append(
                f"| {r.iteration} | {r.verdict.facial_similarity:.1f} "
                f"| {r.verdict.scene_adaptation:.1f} "
                f"| {r.verdict.adherence_score:.1f} "
                f"| {r.verdict.average_score:.1f} "
                f"| {r.strategy} | {_strip_emoji(r.verdict.verdict_label)} | {r.elapsed_seconds:.1f}s |"
            )
    lines.append(f"")
    
    # Convergence graph
    if summary.graph_path or (output_dir / "convergence.png").exists():
        lines.append(f"## Convergence Graph")
        lines.append(f"")
        lines.append(f"![Convergence Graph](convergence.png)")
        lines.append(f"")
    
    # Best Iteration
    lines.append(f"## Best Iteration")
    lines.append(f"")
    best_idx = summary.best_iteration
    if summary.iterations:
        best = summary.iterations[best_idx]
        lines.append(f"**Iteration {best.iteration}** — {_strip_emoji(best.verdict.verdict_label)}")
        lines.append(f"- Facial similarity: {best.verdict.facial_similarity:.1f}/10")
        lines.append(f"- Scene adaptation: {best.verdict.scene_adaptation:.1f}/10")
        lines.append(f"- Adherence: {best.verdict.adherence_score:.1f}/10")
        lines.append(f"- Photorealistic: {'Yes' if best.verdict.is_photorealistic else 'No'}")
        lines.append(f"")
        # Embed best image if exists
        scored_name = f"iter_{best.iteration:02d}_scored.png"
        lines.append(f"![Best iteration]({scored_name})")
        lines.append(f"")
        lines.append(f"### Facial Similarity Rationale")
        lines.append(f"{best.verdict.facial_similarity_rationale}")
        lines.append(f"")
        lines.append(f"### Scene Adaptation Rationale")
        lines.append(f"{best.verdict.scene_adaptation_rationale}")
        lines.append(f"")
        lines.append(f"### Adherence Rationale")
        lines.append(f"{best.verdict.adherence_rationale}")
    lines.append(f"")
    
    # Summary Stats
    lines.append(f"## Summary")
    lines.append(f"")
    lines.append(f"- Total iterations: {len(summary.iterations)}")
    lines.append(f"- Total time: {summary.total_elapsed:.1f}s")
    lines.append(f"- Best facial similarity: {summary.best_facial_similarity:.1f}/10")
    lines.append(f"- Best scene adaptation: {summary.best_scene_adaptation:.1f}/10")
    lines.append(f"- Best adherence: {summary.best_adherence:.1f}/10")
    lines.append(f"- Output directory: `{to_tilde_path(summary.output_dir)}`")
    lines.append(f"")
    
    # Image Gallery
    if summary.iterations:
        lines.append(f"## All Iterations")
        lines.append(f"")
        for r in summary.iterations:
            scored_name = f"iter_{r.iteration:02d}_scored.png"
            lines.append(f"### Iteration {r.iteration}")
            lines.append(f"![Iteration {r.iteration}]({scored_name})")
            lines.append(f"")
    
    content = "\n".join(lines)
    report_path.write_text(content)
    index_path = output_dir / "index.md"
    index_path.write_text(content)
    return report_path


def _strip_emoji(text: str) -> str:
    """Strip emoji for markdown rendering."""
    import re
    emoji_pattern = re.compile(
        "[\U0001F300-\U0001F9FF\U00002702-\U000027B0\U0000FE00-\U0000FE0F"
        "\U0000200D\U00002600-\U000026FF\U0000231A-\U0000231B\U00002B50\U0000274C\U00002705]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub("", text).strip()
